# RIVR Release Build Makefile
#
# Usage:
#   make release-android   — builds signed release AAB with obfuscation
#   make release-ios       — builds release IPA with obfuscation
#   make analyze           — runs flutter analyze
#   make test              — runs unit + widget tests
#
# Prerequisites:
#   - android/key.properties must exist (see Google Drive → RIVR Release Keys/)
#   - lib/services/0_config/shared/config.dart must exist (copy from config.template.dart)
#   - lib/firebase_options.dart must exist (generated by FlutterFire CLI)
#
# Debug symbols are written to build/debug-info/ (gitignored).
# Upload them to Firebase Crashlytics after each release:
#   firebase crashlytics:symbols:upload --app=<APP_ID> build/debug-info/

DEBUG_INFO_DIR := build/debug-info

.PHONY: release-android release-ios analyze test clean

release-android:
	flutter build appbundle --release \
		--obfuscate \
		--split-debug-info=$(DEBUG_INFO_DIR)/android

release-ios:
	flutter build ipa --release \
		--obfuscate \
		--split-debug-info=$(DEBUG_INFO_DIR)/ios

analyze:
	flutter analyze

test:
	flutter test

clean:
	flutter clean
